# Generated by Django 2.2.1 on 2020-06-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200623_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ex',
        ),
    ]
