# Generated by Django 2.2.1 on 2020-06-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_ex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.TextField(blank=True, help_text='자기 소개를 작성하세요.'),
        ),
    ]
