# Generated by Django 2.2.1 on 2020-06-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200623_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='user/profile_pic', verbose_name='프로필 사진'),
        ),
    ]
