# Generated by Django 2.2.1 on 2020-06-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
    ]
