# Generated by Django 2.2.1 on 2020-06-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='pub_date',
        ),
    ]
